### ISSUE TITLE
.Insert .Update issue

### ISSUE THREAD

**Issue by pgawlowski** [3lvis/Sync#389] opened 2017-03-21 15:03 UTC
Let's assume JSONModel objects CartEntity, CartEntry - both got correct primaryKeys.

In CoreData CartEntryEntity got a relation to CartEntity, in JSONModel not.

I'm preparing data like this:
```
cartEntry.quantity = quantity
var dictionary = cartEntry.toDictionary() as! [String: Any]
dictionary["cart"] = cart.toDictionary as! [String: Any]
```
next 
`        Sync.changes([dictionary], inEntityNamed: entity, dataStack: self.dataStack!, operations: [ .Update, .Insert], completion: { (error) in
            completion()
        })
`

and everything seems to be perfect. I've got a cart with cartEntry and whole bunch of correct data.

However performing it again with new quantity (dictionary is totally the same but the quantity has changed) doesn't affect cartEntry - quantity is same.

Interesting thing - everything updates fine if I pass cart and update CartEntity not CartEntry. 

Why?

**Comment by 3lvis** [comment] 2017-03-21 17:49
@pgawlowski Hi! Having an screenshot of your JSON model and the JSON that you're using will help me to reproduce your issue, could you help me sharing that?

**Comment by pgawlowski** [comment] 2017-03-22 07:48
Printed dictionary structure I'm trying to update
`[
  "quantity": 13,
  "cart": [
    "entries": <__NSSingleObjectArrayI0x61800000f800>({
      code=4812254;product={
        code=4812254;description="";manufacturer=Canon;name="500D + 18-55mm IS + EF-S 55-250 IS";price={
          currencyIso=USD;formattedValue="$927.89";priceType=BUY;value="927.89";
        };stock={
          stockLevel=349;stockLevelStatus=inStock;
        };summary="EOS 500D + 18-55mm IS + EF-S 55-250 IS - 15.1 MP CMOS, Full HD (1080p), 3.4fps, 3.0\U201d Clear View LCD, DIGIC 4, 9-point AF";
      };quantity=12;
    }),
    "deliveryItemsQuantity": 0,
    "totalItems": 0,
    "code": 0
  ],
  "code": 4812254,
  "product": {
    code=4812254;description="";manufacturer=Canon;name="500D + 18-55mm IS + EF-S 55-250 IS";price={
      currencyIso=USD;formattedValue="$927.89";priceType=BUY;value="927.89";
    };stock={
      stockLevel=349;stockLevelStatus=inStock;
    };summary="EOS 500D + 18-55mm IS + EF-S 55-250 IS - 15.1 MP CMOS, Full HD (1080p), 3.4fps, 3.0\U201d Clear View LCD, DIGIC 4, 9-point AF";
  }
]`

<img width="599" alt="screen shot 2017-03-22 at 08 14 03" src="https://cloud.githubusercontent.com/assets/9845024/24187114/d4fd44d4-0edb-11e7-90ba-313db2790422.png">

First sync creates proper entry in core-data. I've got cartEntry + related cart + related product. However trying to achieve update on cartEntry (with new quantity and same structure as above) makes no result. 

What I've discovered, same operation on cart entity, with new quantity of cartEntry I want to update have a correct result.

**Comment by 3lvis** [comment] 2017-10-30 22:11
Hi @pgawlowski,

I know it's been some time and I'm not able to reproduce the issue, just hoping it was fixed in the newest release.

**Closed by 3lvis** 2017-10-30 22:11 UTC
Labels: needs-more-info
