### ISSUE TITLE
Nested data including fully nested objects and id only references

### ISSUE THREAD

**Issue by wainglaister** [3lvis/Sync#237] opened 2016-07-02 18:24 UTC
Not sure if this has been covered before, scenario:

You have an object which contains multiple types of nested objects, some of those nested objects are also related to each other so they contain references to each other. These secondary references don't need to be anything more than an id (strictly speaking).

Like a group with teams and members, where each member is in a team.

Currently this doesn't work properly, I guess depending on the processing order, because the members are processed before the teams so when it tries to process the team id it doesn't find it. I know the missing item is explicitly documented and to be careful, but in this case the data is all there, just some isn't processed yet.

A solution for this would be to process all of the complete nested objects first, then run a second pass to complete any id only relationships. I don't know how much effort that would be. Interested in your thoughts on this, or any other solutions.

Alternate would be a client piece of logic to find the nested items that are expected to be complete and to process those first. Not a very nice solution but undoubtedly quicker to implement right now...

**Comment by 3lvis** [comment] 2016-07-02 22:16
Hi @wainglaister!

I think we could do something about your use case, although I'm not sure if I fully understand what you're trying to achieve. Would you mind providing an example of a JSON file or JSON files, and your Core Data model to reproduce this in a unit test?

Thanks!

**Comment by wainglaister** [comment] 2016-07-03 09:14
Hi @3lvis :)

See the single new commit in https://github.com/wainglaister/Sync/tree/Issue237 for a test case demo. The test is a bit messy as I copied&pasted to put it together quickly but it shows the log of the issue and the test fails as the relationship isn't setup.

**Comment by 3lvis** [comment] 2016-07-03 10:58
I see what you mean now. I think it can be solved with the current set up. I'll put an example when I'm more available. Thanks ❤️

**Comment by normand1** [comment] 2016-08-29 18:55
@3lvis I'd be interested in an example too, thanks!

**Comment by 3lvis** [comment] 2016-12-01 19:36
Hi had a second look, given the JSON:

```json
{
  "id": 1,
  "name": "PS",
  "memberships": [
    {
      "id": 3,
      "team_id": 5,
      "name": "bob"
    }
  ],
  "teams": [
    {
      "name": "Pro Sprots",
      "id": 5
    }
  ]
}
```

I'm afraid you have to process the teams first before Sync knows about matching to the `team_id`.

**Comment by 3lvis** [comment] 2016-12-01 19:37
Sorry for not being more helpful here, if you have any suggestions let me know and I'll create a detailed issue to follow up.

**Comment by 3lvis** [comment] 2016-12-01 19:51
Funny, enough. I've noticed if Sync processed first teams, then memberships this works.

https://github.com/SyncDB/Sync/pull/336

**Comment by 3lvis** [comment] 2016-12-01 19:53
We could probably sort the relationships based on how they come from the backend https://github.com/SyncDB/Sync/blob/8337de7fb7370fbc431e968f325971fb494c176e/Source/Sync/NSEntityDescription%2BSync.swift#L8

**Comment by 3lvis** [comment] 2016-12-01 19:57
Reopening this since that's actually something we could do :D

**Comment by 3lvis** [comment] 2017-10-30 22:24
Closing this and leaving the PR.

**Closed by 3lvis** 2017-10-30 22:24 UTC
