### ISSUE TITLE
To-many ordered relationship crash

### ISSUE THREAD

**Issue by kikanny** [3lvis/Sync#453] opened 2017-11-20 21:18 UTC
Hey 3lvis, looks like there is a bug with an ordered relationship in the sync_toManyRelationship method. 
```
if relationship.isOrdered {
                        let objects: [NSManagedObject]
                        if let safeLocalObjects = safeLocalObjects {
                            objects = safeLocalObjects
                        } else {
                            objects = try managedObjectContext.fetch(request) as? [NSManagedObject] ?? [NSManagedObject]()
                        }
                        for safeObject in objects {
                            let currentID = safeObject.value(forKey: safeObject.entity.sync_localPrimaryKey())!
                            let remoteIndex = remoteItems.index(of: currentID)
                            let relatedObjects = self.mutableOrderedSetValue(forKey: relationship.name)

                            let currentIndex = relatedObjects.index(of: safeObject)
                            if currentIndex != remoteIndex && currentIndex != NSNotFound {
                                relatedObjects.moveObjects(at: IndexSet(integer: currentIndex), to: remoteIndex)
                            }
                        }
}
```
In the code above, I'm getting range out of bounds crash in the moveObjects call if remoteIndex is greater than the max index in relatedObjects. This makes sense considering there is no check in place. I'm confused about the purpose of this block of code? I was thinking of just adding a simple check to make sure remoteIndex < relatedObjects.count before the moveObjects method is called. What do you think?

**Comment by 3lvis** [comment] 2017-11-30 19:48
Hi @kikanny,

First of all, sorry for taking so long to reply. Could you help me out with a way to reproduce this so I can add a unit test?

**Comment by 3lvis** [comment] 2017-11-30 19:48
If I understood correctly, it means that the index of the element coming from the server is after the element located in the database?

**Comment by 3lvis** [comment] 2018-02-10 12:43
I'm sure this is still an issue sadly I haven't been working much with sorted relationships, I usually use unsorted relationships then sort using NSFetchResultsController and NSSortDescriptors.

**Comment by kikanny** [comment] 2018-02-13 16:32
@3lvis I'm sorry! I got very busy and forgot about this. For now, I've removed this block of code in our apps. To give you an idea, I've modified the 237.json file to the following.

`[
 {
    "id": 1,
    "slides": [
      {
        "id": 3
      },
      {
        "id": 2
      },
      {
       "id": 1
      }
    ]
 }
]
`
Now, if you run the test327OrderedToMany() test, you should see the out of bounds crash.

**Comment by rebe1one** [comment] 2019-04-26 19:39
@kikanny looks like this was fixed and merged!

**Comment by 3lvis** [comment] 2019-04-26 22:22
Correct! Closing :)

**Closed by 3lvis** 2019-04-26 22:22 UTC
